name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COCOV_REPOSITORY_TOKEN: ${{ secrets.COCOV_REPOSITORY_TOKEN }}
      COCOV_API_URL: ${{ secrets.COCOV_API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare coverage-reporter
        run: |
          curl -sSL https://vito.io/private/coverage-reporter > .coverage-reporter
          chmod +x .coverage-reporter
          ./.coverage-reporter prepare

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test a --watchAll=false

      - name: Push coverage report
        run: ./.coverage-reporter submit

  build:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        file: Dockerfile
        tags: cocov/web:dev
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Trigger update
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: cocov/update
