name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cocov/web:dev
    - name: Push Docker Image
      run: docker push cocov/web:dev
